

CREATE TABLE MEMBERAUTH(
	ID VARCHAR(20) PRIMARY KEY,
	AUTH VARCHAR2(20)
);

CREATE TABLE AUTHORIZEDSTAMP(
	ID VARCHAR2(20) PRIMARY KEY,
	STAMP_IMAGE_LINK VARCHAR2(2000) UNIQUE,
	FOREIGN KEY(ID) REFERENCES MEMBERAUTH(ID)
);

CREATE TABLE AUTHORIZATIONTEMPLATE(
	TEMPLATE_SEQ NUMBER PRIMARY KEY,
	TEMPLATE_TYPE VARCHAR2(20) UNIQUE,
	TEMPLATE_LINK VARCHAR2(2000)
);

CREATE TABLE AUTHORIZATIONLINE (
	AUTHORIZATION_LINE NUMBER PRIMARY KEY,
	AUTHORIZATION_GROUP NUMBER UNIQUE
);

CREATE TABLE AUTHORIZATIONGROUP(
	AUTHORIZATION_GROUP NUMBER ,
	AUTHORIZED_PERSON VARCHAR2(20),
	AUTHORIZED_STATUS VARCHAR2(10),
	AUTHORIZED_STAMP VARCHAR2(2000),
	ARAM CHAR(1),
	FOREIGN KEY(AUTHORIZATION_GROUP) REFERENCES AUTHORIZATIONLINE(AUTHORIZATION_GROUP),
	FOREIGN KEY(AUTHORIZED_PERSON) REFERENCES MEMBERAUTH(ID)
);

CREATE TABLE "AUTHORIZATION" (
	AUTHORIZATION_SEQ NUMBER PRIMARY KEY,
	TEMPLATE_TYPE VARCHAR2(20),
	ID VARCHAR2(20),
	AUTHORIZATION_LINE NUMBER,
	FILE_SEQ CHAR(1),
	COMPLAIN VARCHAR2(4000),
	REGDATE DATE,
	TITLE VARCHAR2(1000),
	CONTENT VARCHAR2(4000),
	FOREIGN KEY(ID) REFERENCES MEMBERAUTH(ID),
	FOREIGN KEY(TEMPLATE_TYPE) REFERENCES AUTHORIZATIONTEMPLATE(TEMPLATE_TYPE),
	FOREIGN KEY(AUTHORIZATION_LINE) REFERENCES AUTHORIZATIONLINE(AUTHORIZATION_LINE)
);

CREATE TABLE AUTHORIZATIONFILE(
	FILE_SEQ NUMBER PRIMARY KEY,
	AUTHORIZATION_SEQ NUMBER,
	FILE_ORIGIN_FNAME VARCHAR2(2000),
	FILE_STORED_FNAME VARCHAR2(2000),
	FILE_SIZE NUMBER,
	FILE_REGDATE DATE,
	FOREIGN KEY(AUTHORIZATION_SEQ) REFERENCES "AUTHORIZATION"(AUTHORIZATION_SEQ)
);

CREATE SEQUENCE AUTHORIZATIONLINE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUTHORIZATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUTHORIZATIONTEMPLATE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUTHORIZATIONGROUP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUTHORIZATIONFILE_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO MEMBERAUTH (ID,AUTH)
VALUES('CENTER01','ROLE_CENTER');
INSERT INTO MEMBERAUTH (ID,AUTH)
VALUES('STUDENT01','ROLE_STUDENT');
INSERT INTO MEMBERAUTH (ID,AUTH)
VALUES('goodee1234','ROLE_ACADEMY');

--------------------------- ���� �׽�Ʈ

--���� ���ø� ���(������)
INSERT INTO AUTHORIZATIONTEMPLATE(TEMPLATE_SEQ,TEMPLATE_TYPE,TEMPLATE_LINK)
VALUES(AUTHORIZATIONTEMPLATE_SEQ.NEXTVAL,'�ް�','/Files/un/asdifnosng.png');
--���� ���ø� ����(�����)
SELECT TEMPLATE_SEQ,TEMPLATE_TYPE,TEMPLATE_LINK
	FROM AUTHORIZATIONTEMPLATE
	WHERE TEMPLATE_TYPE ='�ް�';
--���� ���ø� ����(������)
DELETE FROM AUTHORIZATIONTEMPLATE WHERE TEMPLATE_TYPE = '�ް�';
--���� ���ø� ����(������)
UPDATE AUTHORIZATIONTEMPLATE SET TEMPLATE_LINK='/Files/un/asdifnosEE.png' WHERE TEMPLATE_TYPE='�ް�';

--���� ���� ���(�̹��� ���)(�����)
INSERT INTO AUTHORIZEDSTAMP(ID,STAMP_IMAGE_LINK)
VALUES ('STUDENT01','/images/stamp/ss.png');
--���� ���� ����(�̹��� ���)(�����)
UPDATE AUTHORIZEDSTAMP SET STAMP_IMAGE_LINK='/images/stamp/ssf.png' WHERE ID='STUDENT01';
--���� ���� ��� ���� ��ȸ(���� ���� �ۼ��Ҷ� ������ �ñ�� �� ����)(�����)
SELECT ID,STAMP_IMAGE_LINK FROM AUTHORIZEDSTAMP WHERE ID ='STUDENT01';

--���� ���� �ۼ�(�����ۼ�)(�����) 1��
--���� ���� ����ȸ(����ȸ)(�����) 1��
--���� ���� ��ȸ(��ȸ)(�����) ������
--���� ���� ��ȸ -> �Ϸ� , �̿Ϸ�
--���� ���� �˻�(���� ���� ������)(�����) ������
--���� ���� ����(�ݷ����뿡 �����߰�)(�����) �Ѱ� UPDATE

--����� ���(�����ۼ�)(�����) �Ѱ� 
--����� ��ȸ(����ȸ)(�����) ������ ����� �����ؼ����

--����� ���翩�� ����(���� �ݷ� �뺸ó��)(�����)
--����� �������� ����(���� �ο� �˶� ó��)(�����)

--���� �� ��϶� �ʿ��Ѱ�)
--���̵� �˻� (USER ID �κп� �ش� �˻��� �÷��� ���� �ϸ� ���� �� ���� -> �б�� �÷� ����� ������ )(�����)
SELECT a.* FROM MEMBERAUTH m JOIN AUTHORIZATIONGROUP a ON m.ID = a.AUTHORIZED_PERSON WHERE a.AUTHORIZED_PERSON ='CENTER01';
SELECT a.* FROM MEMBERAUTH m JOIN AUTHORIZATION a ON m.ID = a.ID;

SELECT AUTH FROM MEMBERAUTH WHERE ID='STUDENT01';

SELECT a.AUTHORIZED_PERSON ID FROM MEMBERAUTH m JOIN AUTHORIZATIONGROUP a ON m.ID = a.AUTHORIZED_PERSON JOIN MEMBERAUTH m2 ON m2.ID =m.ID WHERE m2.AUTH =(SELECT AUTH FROM MEMBERAUTH WHERE ID='CENTER01');
SELECT a.ID ID FROM MEMBERAUTH m JOIN AUTHORIZATION a ON m.ID = a.ID JOIN MEMBERAUTH m2 ON m2.ID =m.ID WHERE m2.AUTH =(SELECT AUTH FROM MEMBERAUTH WHERE ID='STUDENT01');


INSERT INTO AUTHORIZATIONLINE (AUTHORIZATION_GROUP ,AUTHORIZATION_LINE )
VALUES (AUTHORIZATIONGROUP_SEQ.NEXTVAL,AUTHORIZATIONLINE_SEQ.NEXTVAL);
INSERT INTO AUTHORIZATION(AUTHORIZATION_SEQ ,ID ,AUTHORIZATION_LINE ,TEMPLATE_TYPE ,FILE_SEQ ,COMPLAIN ,TITLE ,CONTENT ,REGDATE )
VALUES(AUTHORIZATION_SEQ.NEXTVAL,'STUDENT01',AUTHORIZATIONLINE_SEQ.NEXTVAL,'�ް�',NULL,NULL,'����','����',SYSDATE);
INSERT INTO AUTHORIZATIONGROUP (AUTHORIZATION_GROUP ,AUTHORIZED_PERSON ,AUTHORIZED_STAMP ,AUTHORIZED_STATUS ,ARAM )
VALUES (AUTHORIZATIONGROUP_SEQ.NEXTVAL,'STUDENT01',(SELECT STAMP_IMAGE_LINK FROM AUTHORIZEDSTAMP WHERE ID ='STUDENT01'),'���','N' );
INSERT INTO AUTHORIZATIONGROUP (AUTHORIZATION_GROUP ,AUTHORIZED_PERSON ,AUTHORIZED_STAMP ,AUTHORIZED_STATUS ,ARAM )
VALUES ('1','CENTER01','/images/file/gg.png','���','N' );



--���� ���(�����)
--���� ��ȸ(�����)
