ALTER TABLE BOARD ADD CONSTRAINT BOARD_FK FOREIGN KEY (USERID) REFERENCES STUDENT(ID);

SELECT BOARDSEQ , USERID ,
		CONTENT , REGDATE
FROM (SELECT BOARDSEQ , USERID ,
		CONTENT , REGDATE, ROW_NUMBER () OVER(ORDER BY BOARDSEQ DESC)RN
	FROM REPLY_BOARD a WHERE DELFLAG = 'N' AND BOARDSEQ = '1')
	WHERE RN BETWEEN '1' AND '3'
	

	SELECT COUNT(*)
	FROM REPLY_BOARD rb 
	WHERE BOARDSEQ ='1';

	SELECT * 
	FROM REPLY_BOARD rb 
	
ALTER TABLE ATTACH_FILE ADD OWNER VARCHAR2(30)